<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>Dataset_Template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*(#).*$
?</string>
			<key>name</key>
			<string>comment.line.number-sign.maker_syntax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>section.data.name.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>section.data.name.middle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>section.data.name.value</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>section.data.name.equote</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>section.data.name.end</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(name":")((.*?)("))(,)</string>
			<key>name</key>
			<string>section.data.name</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>section.data.validator.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>section.data.validator.middle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>section.data.validator.value</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>section.data.validator.equote</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>section.data.validator.end</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(validator":")((.*?)("))(,)</string>
			<key>name</key>
			<string>section.data.validator</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>section.data.dependencies.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>section.data.dependencies.middle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>section.data.dependencies.value</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>section.data.dependencies.equote</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>section.data.dependencies.end</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(dependencies":")((.*?)("))(,)</string>
			<key>name</key>
			<string>section.data.dependencies</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>section.data.ui.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>section.data.ui.middle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>section.data.ui.value</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>section.data.ui.equote</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>section.data.ui.end</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(ui":")((.*?)("))(,)</string>
			<key>name</key>
			<string>section.data.ui</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>section.data.field.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>section.data.field.middle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>section.data.field.value</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>section.data.field.equote</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(field":")((.*?)("))</string>
			<key>name</key>
			<string>section.data.field</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>! -Validators-</string>
			<key>end</key>
			<string>~Validators~</string>
			<key>name</key>
			<string>section.validator</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>! -Keys-</string>
			<key>end</key>
			<string>~Keys~</string>
			<key>name</key>
			<string>section.key</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>! -Data List-</string>
			<key>end</key>
			<string>~Data List~</string>
			<key>name</key>
			<string>section.datalist</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>! -Dependencies-</string>
			<key>end</key>
			<string>~Dependencies~</string>
			<key>name</key>
			<string>section.dependencies</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.dataset_template</string>
	<key>uuid</key>
	<string>babc7c14-1861-48fb-94d5-681801716f0f</string>
</dict>
</plist>
